### ISSUE TITLE
DEFAULT_PATH_LEAF_TO_NULL did not work with $..path(deep scan)

### ISSUE THREAD

**Issue by lancelotnull** [json-path/JsonPath#222]
like the following json
[
   {
      "name" : "john",
      "gender" : "male"
   },
   {
      "name" : "ben"
   }
]

when I set DEFAULT_PATH_LEAF_TO_NULL and used $..gender，I got ["male"] ，(["male", null] is expected). how I can get expected value?

Thank you!

**Comment by jochenberger** [comment]
It does actually return `["male", null]` on http://jsonpath.herokuapp.com/.

**Comment by jochenberger** [comment]
I think this can be closed.
