### ISSUE TITLE
key set of all the paths present

### ISSUE THREAD

**Issue by ratulmukh** [json-path/JsonPath#260]
Is there a way to get a key set of all the paths present via JsonPath? I didn't find any, and had to use a different JSON parsing library to extract this, and then use that for further processing via JsonPath. It would be nice if there was a method that would just provide this functionality directly.

**Comment by kallestenflo** [comment]
Sorry for late response. Not much time for this project lately but now...

If you are still interested could you please give a simple example outlining the feature? You want to select the keys not the values?

**Comment by jochenberger** [comment]
Close this?

**Comment by kallestenflo** [comment]
Lack of input

**Comment by sonbock** [comment]
select the keys!
