### ISSUE TITLE
Multiple filter criteria in JSON QueryString

### ISSUE THREAD

**Issue by sathishkumarganesan123** [json-path/JsonPath#342]
[{"StartDate":"09/01/2011",
"EndDate":"09/01/2012",
"carrier":"ATT",
"IDCardNumber":"AS1311223334031",
"PType":null,
"ISONumber":"1223334"
},
{
"StartDate":"11/01/2012",
"EndDate":"11/01/ 2013",
"carrier":"ATT",
"IDCardNumber":"AS8311223334082",
"PType":null,
"ISONumber":"1223334"
},
{
"StartDate":"11/01/2012",
"EndDate":"11/01/2013",
"carrier":"VERIZON",
"IDCardNumber":"AS1311223334092",
" PType":null,
"ISONumber":"122222"
}
]

From the above JSON, i wish to filter ISONumber for IDcardNumber AS1311223334092 and carrier VERIZON.

$.[?(@.IDCardNumber== 'AS1311223334092') && ?(@.carrier== VERIZON)].ISONumber

i am getting an error like invalid JSON path in loadrunner. But the same path in working in http://jsonpath.com/? 

Please help me on this.

Also, does it have any problem if a particular element has a mix of null and string values.

**Comment by kallestenflo** [comment]
Try this:

$.[?(@.IDCardNumber == 'AS1311223334092' && @.carrier == 'VERIZON')].ISONumber

you can experiment here http://jsonpath.herokuapp.com

**Comment by sathishkumarganesan123** [comment]
Actually this works in the JSON validator. But throwing an error in loadrunner like no matches found.

**Comment by kallestenflo** [comment]
Sounds like an issue with loadrunner.

**Comment by jochenberger** [comment]
Can we close this then?
