### ISSUE TITLE
Jayway's JsonPath returns empty array if key in the predicate is not present in JSON Data

### ISSUE THREAD

**Issue by jimsha** [json-path/JsonPath#352]
I am trying evaluate a JSON text using the expression $.sessions[?(@.key=='session3')].value using Jayway JsonPath 2.2.0 library.
JsonText = {
"username": xyz,
"empid": "1",
"sessions": [{
             "key": "session1",
             "value": "java"}, 
             {
             "key": "session2",
             "value": "C"}]
}

It return empty object instead of null even if I am using Option.DEFAULT_PATH_LEAF_TO_NULL

I tried evaluating this through http://jsonpath.herokuapp.com/ and there also it returns empty array. Please help

**Comment by jochenberger** [comment]
An empty list is expected, see https://github.com/json-path/JsonPath#what-is-returned-when. `DEFAULT_PATH_LEAF_TO_NULL` would only have an effect if your `sessions` array contained an object that does not have the `key` property.

**Comment by kallestenflo** [comment]
Not an issue
