### ISSUE TITLE
Getting Missing property when node has tag like "profile.datasource"

### ISSUE THREAD

**Issue by saquibgul** [json-path/JsonPath#360]
I have a JSON like this:
```
{
"spring.profiles": "dev"
}
```
now as I try to get value with "$.spring.profiles" , I get missing property error.

**Comment by kallestenflo** [comment]
Try bracket notation.

$['spring.profiles']

**Comment by saquibgul** [comment]
thanks alot, square brack [] and single quote ' ' did work

**Comment by jochenberger** [comment]
Can we close this then?

**Comment by saquibgul** [comment]
Yes this is resolved
