### ISSUE TITLE
DocumentContext to org.json.JSONObject?

### ISSUE THREAD

**Issue by DavidThi808** [json-path/JsonPath#374]
Hi all;

I want to both validate JSON and then use json-path for JPath queries. The validation is using [json-schema](https://github.com/everit-org/json-schema) which wants a JSONObject of the JSON to validate it. json-path wants a String or InputStream.

In a perfect world both could work off the same object as it's read in. However json-schema is built around the JSONObject and changing that would be a major re-write. And so, the next best is parse using json-path and then from the DocumentContext get a JSONObject of it.

Is there a way to do this? If not, then is the best way to read in the JSON as a JSONObject, feed that to the schema validation, and then get the String representation of that to pass to json-path?

thanks - dave

**Comment by kallestenflo** [comment]
This is currently not supported. 
See #355
