### ISSUE TITLE
Q: Is a compiled JsonPath thread-safe?

### ISSUE THREAD

**Issue by aozarov** [json-path/JsonPath#384]
I am using a ReadContext which was created with JsonOrg configuration, which AFAIK, is thread safe.
I would like to be able to invoke its read(JsonPath) call using static/shared JsonPath compiled expressions.
I could not tell for sure if that is supported and if compiled JsonPath expressions are thread-safe (or even can be reused).

**Comment by aozarov** [comment]
I just noticed the use of CacheProvider in JsonContext which leads me to believe that indeed JsonPath is indeed thread-safe.

**Comment by kallestenflo** [comment]
It should be thread safe.
