### ISSUE TITLE
converter JSON

### ISSUE THREAD

**Issue by edgiru** [json-path/JsonPath#386]
Help to understand what to write in a line converter JSON
![screenshot_2017-08-29-17-52-43](https://user-images.githubusercontent.com/4624056/29828525-9ebfa226-8ce5-11e7-82e0-6905d56d6a44.jpg)
from mqtt goes this line:
{"system":{"hostname":"test","uptime":56858,"rssi":-59,"freemem":13264},"sensors":{"dsw1":28.9,"dsw2":28.8,"dsw3":28.1,"dsw4":25.5,"ping":1},"gpio":{"16":0},"pwm":{"0":120}}

is always written null
![screenshot_2017-08-29-18-15-44_1](https://user-images.githubusercontent.com/4624056/29828738-47210cb6-8ce6-11e7-8290-79aa96ff230b.jpg)

**Comment by kallestenflo** [comment]
I don't see how this is related to this project.
