### ISSUE TITLE
Error if key has a comma ","

### ISSUE THREAD

**Issue by ecovirtual** [json-path/JsonPath#400]
Given this JSON: 
`{
  "Key with, coma": ["I have a comma", "Does't work"],
  "Key without coma": ["I don't have a coma", "It works"]
}
`
The following throws an error: 
`$['Key with, comma'][*]`

No problem with this: 
`$['Key without comma'][*]`

Is there a way to escape the comma?

**Comment by marcbux** [comment]
Was there any reply / fix / solution for this? I have the same question and am unsure whether this is a bug in the implementation or I'm supposed to escape the comma. It feels kinda weird having to escape a comma in a quoted string...

**Comment by jlolling** [comment]
A Key with a comma - really? Do you are aware such requirements causing a unmaintainable complexity? Sorry if I had something to say here, such requirements would never ever implemented!

**Comment by hf-kklein** [comment]
@jlolling I personally don't understand the problem nor the complexity that arises with commas in a key. I'd be glad if you could provide some insight or details here. As @marcbux mentioned it feels just weird, to escape a comma like you used to escape quotes.

On the [Heroku App](https://jsonpath.herokuapp.com/) both the Gatling and Goessner implementation work perfectly fine if you use the path `$['Key with, coma']`. Only the Jayway implementation requires escaping `$['Key with\, coma']` for the minimal example [provided above](https://github.com/json-path/JsonPath/issues/400#issue-263167930).
