### ISSUE TITLE
Support for element names containing colons

### ISSUE THREAD

**Issue by sazzer** [json-path/JsonPath#436]
I'm trying to use JsonPath to assert payloads in the HAL Hypermedia format. This includes the concept of CURIEs, and thus Link Definition Objects where the Relation has a colon in the name.

As an example taken straight out of the RFC:
```
   {
     "_links": {
       "self": { "href": "/orders" },
       "curies": [{
         "name": "acme",
         "href": "http://docs.acme.com/relations/{rel}",
         "templated": true
       }],
       "acme:widgets": { "href": "/widgets" }
     }
   }
```

In order to assert this, I need to assert that `_links/acme:widgets/href` is equal to `/widgets`. Unfortunately:

* `context.getValue("_links/acme:widgets/href")` throws a JXPathNotFoundException
* `context.getValue("_links['acme:widgets']/href") == null`
* `context.getValue("_links['acme:widgets']") == context.getValue("_links")`
  * I assume because of the "Array Slice Operator" rules
* `context.getValue("_links['acme\\:widgets']/href") == null`
  * This actually acts the same as if the '\\' escape wasn't there
* `context.getValue("_links/acme\\:widgets/href")` throws a JXPathInvalidSyntaxException

So, is there some way of correctly expressing a JsonPath that has a colon in the element name? And if not, can there be please? :)

Cheers

**Comment by ochubey** [comment]
@sazzer you should try to use escape sequence like this `_links.'acme:widgets'.href`

**Comment by sazzer** [comment]
If I use periods instead of slashes then I don't get a value - instead it always returns null.

If I use period and single quotes, like you say, I get:
`context.getValue("_links.'acme:widgets'.href")` throws `Invalid XPath: '_links.\'acme:widgets\'.href'. Syntax error after: '_'`

If I use slashes and single quotes I get:
`context.getValue("_links/'acme:widgets'/href")` throws `Invalid XPath: '_links/\'self\'/templated'. Syntax error after: '_links/'`

**Comment by sazzer** [comment]
Apologies. Like a complete idiot, I'm actually using a completely different library and getting different results! The above is all completely correct for "JXPath". When I try it with "JsonPath", it does indeed do as you say.
