### ISSUE TITLE
Periods in key

### ISSUE THREAD

**Issue by dwatrous** [json-path/JsonPath#482]
I have a JSON document like this

```
{
    "CATEGORY":{
    "some.key.name":"myname",
    "some.key.url":"myurl"
    }
}
```

I want to do something like this

```
        assertThat(myresponse.body().asString(), hasJsonPath("CATEGORY.some.key.name", equalTo("myname")));
```

Unfortunately this fails because hasJsonPath assumes the period represents depth in the JSON document. Is there some way to perform this validation?

**Comment by hf-kklein** [comment]
You could use the backet notation: `$.CATEGORY['some.key.name']`
Also works for keys containing spaces etc.

**Comment by dwatrous** [comment]
This worked great. Thank you.

**Comment by d41k4n** [comment]
The following jsonPath

`$['value']['kmf.services:name=single-cluster-monitor,type=produce-service']['produce-availability-avg']`

produces the following error:

com.jayway.jsonpath.InvalidPathException - Found empty property at index 74

**Comment by hf-kklein** [comment]
@d41k4n The comma is a problem. You need to escape it using `\,` instead of just `,` ( see also #400 and #487 ).
