### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by FranklinYu** [json-path/JsonPath#500]
There doesn't seem to be any activity for this entire year.

**Comment by fugui** [comment]
I also have this question.

**Comment by Emsys** [comment]
I also have this question.... i still waiting the support for custom function.
https://github.com/json-path/JsonPath/pull/286

**Comment by henrik242** [comment]
@kallestenflo Any plans on doing a new release any time soon?  It would be greatly appreciated :)

**Comment by kallestenflo** [comment]
Yes! Some time in Q1 is the plan.

**Comment by FranklinYu** [comment]
Will close this issue after the release. 🎉

**Comment by maxpaynebupt** [comment]
> Yes! Some time in Q1 is the plan.

Did the Q1 mean 2021's Q1? I used to think it should be 2020's Q1.........Or will become 2022's Q1?^_^

**Comment by ProTip** [comment]
AWS uses JsonPath. Are they using a custom implementation, a fork, or something else internally? Would be great to see some of the PRs merged and other activity.

**Comment by FranklinYu** [comment]
Glad to see the release 2.5.0! How time flies. Thank you for picking it up!
