### ISSUE TITLE
SLF4J Printing to console and no way to disable it

### ISSUE THREAD

**Issue by andrfgs** [json-path/JsonPath#505]
I don't exactly know who had the brilliant idea of forcing users to use SLF4J without having any way to disable or preventing it to output to console. 

Basically, for any application that requires a clear log, this library is now useless till this issue is solved.

You should never enforce someone to use a logger.

**Comment by kallestenflo** [comment]
Logging can be turned off. This is not an issue. 

https://stackoverflow.com/questions/14544991/how-to-configure-slf4j-simple

**Comment by andrfgs** [comment]
Very well, I apologize then as I was unable to disable it.

**Comment by nkushwah-processia** [comment]
How you solve it can you please share with me
