### ISSUE TITLE
remove debug messages?

### ISSUE THREAD

**Issue by arianaa30** [json-path/JsonPath#510]
Is there any ways to remove the `debug` messages?

I am simply trying to run a code. But when running the jar artifact file, it show the following as the first line:

`0 [main] DEBUG com.jayway.jsonpath.internal.path.CompiledPath  - Evaluating path: $['pageInfo']['pageName']`

How to ignore this line?

**Comment by arianaa30** [comment]
here is the code to be added:

```
LoggerContext logContext = (LoggerContext) LoggerFactory.getILoggerFactory();
ch.qos.logback.classic.Logger log = logContext.getLogger("com.jayway.jsonpath.internal.path.CompiledPath");
log.setLevel(Level.INFO);
```
We also need this in the dependencies:

```
<dependencies>
   <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-api</artifactId>
      <version>2.11.1</version>
   </dependency>
   <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-core</artifactId>
      <version>2.11.1</version>
   </dependency>
   <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>1.2.3</version>
   </dependency>
</dependencies>
```

**Comment by AlexMakesSoftware** [comment]
Can we reopen this? Isn't there a way to turn this off without adding a log4j dependency? Log4j is considered a security vulnerability these days by most organisation's security people.
