### ISSUE TITLE
['store'] in path $ but found 'net.minidev.json.JSONArray'

### ISSUE THREAD

**Issue by LucaOnly** [json-path/JsonPath#521]
i try to use it by example but show me this exception, i don't know how to use it now..,can u help me to solve it  ? or the example is wrong

**Comment by hf-kklein** [comment]
@LucaOnly 
could you please post
- the JSON
- and the JSON path that throws the exception?

The title reads like you're trying to access an element inside an array with a key (`'store'`) instead of an index (e.g. `0`).

**Comment by LucaOnly** [comment]
@hf-kklein  hi, i am so happy that you reply this issue such quickly, i have finished it by using $..store ,the exception shows that i want to operate a jsonArray by $.store.* ,but $.store.* looks like to analyse jsonObject or gson. In additional,I am a developer working to make medical data clean and good for data analysis, so i use mongodb to collect medical data ,i have to make a tool for getting jsonNode by path(eg: store.book.name) ,i think it is important to make tools quickly and easy to use,especially easily to get jsonNode ,but it seems that this tool dosen't has this ability.I think this tool can be better if it can finish this .

**Comment by hf-kklein** [comment]
So is your problem solved now? Or do you still get an exception? If yes, please post
- the original json
- the json path you're trying to use
- the **expected** result

**Comment by LucaOnly** [comment]
@hf-kklein  yes ,this  can be cloese, i am so haapy u can help me .i will pull this project after work and learn the code,it may help me in the future.best wishes

**Comment by LucaOnly** [comment]
i make a simple tools for json analysis. if you need ,i can share u it.

**Comment by hf-kklein** [comment]
> yes ,this can be cloese

so, please close it yourself ;-)

**Comment by LucaOnly** [comment]
i use my tools to handle 10 million data ,it works very well .if u need i can share it to yourself
