### ISSUE TITLE
Negative array index fails to parse, throws exception

### ISSUE THREAD

**Issue by cse-garylo** [json-path/JsonPath#567]
Here is my json:
```
[
  {
    "commandLine": "cmd /c echo \\\"boo\"\\",
    "exitCode": 0,
    "stdOut": [
      "\\\"boo\"\\"
    ],
    "stdErr": []
  }
]
```
My path is: $[0].stdOut[-1]

It seems to work using the Jayway implementation on the [herokuapp](https://jsonpath.herokuapp.com/?path=$[0].stdOut[-1]) but when executing my code using the library I'm getting "Failed to parse ArrayIndexOperation: -1"

I've debugged it to the parse() method of ArrayIndexOperation.
This section doesn't seem to allow the '-' char and ends up throwing the exception:
```
            if (!Character.isDigit(c) && c != ',' && c != ' ') {
                throw new InvalidPathException("Failed to parse ArrayIndexOperation: " + operation);
            }
```

**Comment by alexsilv** [comment]
Hello.
Reading [here](https://goessner.net/articles/JsonPath/) you will find square brackets index always must start by 0.

**Comment by Alanscut** [comment]
hi @cse-garylo , that's weired, I verified it and it seems to be ok.
here is my JsonPath version.
```
<!-- https://mvnrepository.com/artifact/com.jayway.jsonpath/json-path -->
<dependency>
    <groupId>com.jayway.jsonpath</groupId>
    <artifactId>json-path</artifactId>
    <version>2.4.0</version>
</dependency>

```
and this is junit test:
![issue_567](https://user-images.githubusercontent.com/21104054/72066559-dfcb5600-331b-11ea-8576-fa670f884f80.png)

**Comment by cse-garylo** [comment]
Thank you @Alanscut, it looks like the error I was getting was just happening in the version 2.2.0 I was using.
It works fine in 2.3.0 and 2.4.0.
