### ISSUE TITLE
JsonParh.parse() returning null for a correct query

### ISSUE THREAD

**Issue by mNadimMat** [json-path/JsonPath#575]
Hello, 
I tried to query the following JSON 

> {
"types": {
"TER": "PERCENTAGE",
"AUM": "AMOUNT",
"NNA": "AMOUNT",
"NAV": "AMOUNT",
"DISTRIBUTION_POLICY": "STRING",
"ISIN": "STRING",
"INCEPTION_DATE": "DATE",
"TICKER": "STRING",
"INDEX_TICKER": "STRING",
"FUND_TYPE": "STRING",
"REPLICATION_METHOD": "STRING",
"REPLICATION_METHOD_DETAILED": "STRING",
"IS_SWAP_DISPLAYED": "STRING",
"PEA": "STRING",
"FORMATTED_NAV": "STRING",
"SHARE_MARKETING_NAME": "STRING",
"CURRENCY": "STRING",
"MNEMO": "STRING",
"PRODUCT_PIXEL": "STRING",
"PERFORMANCE": "PERCENTAGE"
},
"exceptions": {
"AUM": {
"rules": {
"trimMantissa": true,
"output": "currency",
"mantissa": 1,
"optionalMantissa": true,
"currencyPosition": "postfix",
"average": true,
"spaceSeparated": false,
"forceAverage": "million",
"thousandSeparated": true
},
"extra": {
"currencyDisplay": "code",
"currecyDisplayMode": "PRODUCT_CURRENCY",
"productCurrencyDisplayKey": "CURRENCY",
"defaultCurrency": "-"
}
},
"NNA": {
"rules": {
"trimMantissa": true,
"output": "currency",
"mantissa": 1,
"optionalMantissa": true,
"currencyPosition": "postfix",
"average": true,
"spaceSeparated": false
},
"extra": {
"currencyDisplay": "code",
"currecyDisplayMode": "DEFAULT",
"productCurrencyDisplayKey": "-",
"defaultCurrency": "EUR"
}
},
"TER": {
"rules": {
"trimMantissa": true,
"output": "percent",
"mantissa": 5,
"spaceSeparated": false
},
"extra": {
"divideBy": 100
}
},
"NAV": {
"rules": {
"trimMantissa": true,
"output": "currency",
"mantissa": 4,
"optionalMantissa": true,
"currencyPosition": "postfix",
"average": true,
"spaceSeparated": true
},
"extra": {
"currencyDisplay": "code",
"currecyDisplayMode": "PRODUCT_CURRENCY",
"productCurrencyDisplayKey": "CURRENCY",
"defaultCurrency": "-"
}
}
},
"abbreviations": {
"en-GB": {
"million": "mio",
"billion": "mrd"
},
"es-ES": {
"million": "m",
"billion": "Bn"
},
"it-IT": {
"million": "mln",
"billion": "mld"
},
"fr-FR": {
"million": "mio",
"billion": "mrd"
},
"de-DE": {
"million": "mio",
"billion": "mrd"
}
},
"overrideLocale": null,
"default": {
"PERCENTAGE": {
"rules": {
"output": "percent",
"mantissa": 2,
"spaceSeparated": true
}
},
"DATE": {
"dateType": "numeric"
},
"AMOUNT": {
"rules": {
"trimMantissa": true,
"output": "currency",
"mantissa": 2,
"optionalMantissa": true,
"currencyPosition": "prefix",
"average": false,
"spaceSeparated": true
},
"extra": {
"currencyDisplay": "code",
"negativeSignPosition": "PREFIX_TO_EVERYTHING"
}
},
"NUMBER": {
"rules": {
"mantissa": 2
}
},
"OTHER": {}
}
}

The library works fine except for one entry and returns null to it, the corresponding JsonPath query is **$.exceptions.AUM.rules** . 
I tried querying it with jsonpath.com and the query works just fine except that it returns null in my case.
Thank you in advance.

**Comment by hf-kklein** [comment]
Did you try to reproduce the bug on [jsonpath.herokuapp.com](https://jsonpath.herokuapp.com/)? This site actually uses the library managed in this repository and it works just fine for me; Does not return `null` but 
```
{
   "trimMantissa" : true,
   "output" : "currency",
   "mantissa" : 1,
   "optionalMantissa" : true,
   "currencyPosition" : "postfix",
   "average" : true,
   "spaceSeparated" : false,
   "forceAverage" : "million",
   "thousandSeparated" : true
}
```

**Comment by mNadimMat** [comment]
Hello @hf-kklein ,
Thank you for your answer, i actually figured out the issue .
I was binding the output of this instruction `JsonPath.parse(jsonValue).read(jsonPath, classType);` to a a POJO that missed some of the properties included in the JSON that i'm querying.
So,issue closed. I'm here for any help .
Thanks.
