### ISSUE TITLE
Null value treated as empty array/object

### ISSUE THREAD

**Issue by GeorgiPetkov** [json-path/JsonPath#576]
Given a property with value null, when reading required properties with wildcard it is treated as an empty array/object. The expected behavior is to be treated as not existing and throw JsonPathException instead of returning empty array.

Problem: I'm unable to differentiate between null and empty array while null is unacceptable by contract. The null value may be at the end as well as in the middle of the path.

I'm using the latest released version 2.4.0. Below is a JUnit test that shows what I'm expecting as a behavior with 2 paths being commented - those fail because they return empty list where an exception is expected.

If you have any ideas how I can change the configuration to suite my case you're welcome. I believe I've tried everything with no success. Also switching to other JSON provider makes things even worse (the results are inconsistent between providers).

```
import com.jayway.jsonpath.Configuration;
import com.jayway.jsonpath.JsonPathException;
import com.jayway.jsonpath.ReadContext;
import org.junit.Test;

import java.util.List;
import java.util.stream.Stream;

import static com.jayway.jsonpath.JsonPath.parse;
import static com.jayway.jsonpath.Option.REQUIRE_PROPERTIES;
import static java.lang.String.format;
import static org.junit.Assert.fail;

public class MissingPropertiesTest {

    private static final String JSON = String.join("\n",
            "{",
            "  \"optional\":null,",
            "  \"requiredEmpty\":[],",
            "  \"requiredWithSingleValidElement\":[{\"required\": \"1\"}],",
            "  \"requiredWithTwoValidElements\":[{\"required\": \"1\"}, {\"required\": \"2\"}],",
            "  \"requiredWithSingleInvalidElement\":[{}],",
            "  \"requiredWithValidAndInvalidElement\":[{\"required\": \"1\"}, {}],",
            "  \"nested\": [",
            "    {",
            "      \"optional\":null,",
            "      \"requiredEmpty\":[],",
            "      \"requiredWithSingleValidElement\":[{\"required\": \"1\"}],",
            "      \"requiredWithTwoValidElements\":[{\"required\": \"1\"}, {\"required\": \"2\"}],",
            "      \"requiredWithSingleInvalidElement\":[{}],",
            "      \"requiredWithValidAndInvalidElement\":[{\"required\": \"1\"}, {}]",
            "    },",
            "    {",
            "      \"optional\":null,",
            "      \"requiredEmpty\":[],",
            "      \"requiredWithSingleValidElement\":[{\"required\": \"2\"}],",
            "      \"requiredWithTwoValidElements\":[{\"required\": \"3\"}, {\"required\": \"4\"}],",
            "      \"requiredWithSingleInvalidElement\":[{}],",
            "      \"requiredWithValidAndInvalidElement\":[{\"required\": \"2\"}, {}]",
            "    }",
            "  ]",
            "}");

    @Test
    public void givenNotExistingPathAndExceptionShouldBeThrown() {
        ReadContext context = parse(JSON, Configuration.builder().options(REQUIRE_PROPERTIES).build());

        // Here's the problem - the commented paths don't throw exception but return empty list instead
        Stream.of(/* "$.optional[*].required", */"$.notExisting[*].required", "$.requiredWithSingleInvalidElement[*].required", "$.requiredWithValidAndInvalidElement[*].required",
                /*"$.nested[*].optional[*].required", */"$.nested[*].notExisting[*].required", "$.nested[*].requiredWithSingleInvalidElement[*].required", "$.nested[*].requiredWithValidAndInvalidElement[*].required")
                .forEach(path -> {
                    try {
                        List<String> values = context.read(path);

                        fail(format("Expected to throw JsonPathException, but instead got '%s' for path '%s'.", values, path));
                    } catch (JsonPathException e) {
                        // expected to fail
                    }
                });
    }
}
```

**Comment by Alanscut** [comment]
@GeorgiPetkov I found the problem lies in `WildcardPathToken.java`
https://github.com/json-path/JsonPath/blob/588d61e9b78d57f56e3e70c1ebcf075488db82a3/json-path/src/main/java/com/jayway/jsonpath/internal/path/WildcardPathToken.java#L34-L50

only when the model is an `array` or `map`, it will search in the next path, or it will do nothing.
maybe #586 will solve your problem.

**Comment by GeorgiPetkov** [comment]
@Alanscut 
The comment "// Here's the problem - the commented paths don't throw exception but return empty list instead" could be removed in the test.
The comments "// shouldn't be returned []" sound better as "// shouldn't return []". Also, these comments make sense only in the context of this issue so a link to it in the code would make sense. For the string, number and boolean cases the corresponding "nested" cases are not added.
Should this code be aware of the configuration? I mean this behavior is expected because the properties are required, otherwise, an empty array seems more appropriate. I'm thinking of the use case where a property doesn't have a specific type and can be both of type string in one case and of type array in another for example. Think of a schema using this feature [Multiple Types](https://cswr.github.io/JsonSchema/spec/multiple_types).
Anyway, that solves the problem in my case.
