### ISSUE TITLE
Validate JsonPath syntax without context

### ISSUE THREAD

**Issue by SaeedZhiany** [json-path/JsonPath#577]
I want to validate a user given JsonPath from its syntax aspect. in other words, I want to make sure the user inputs a valid JsonPath structure, no matter what is the Json object itself. (Json object will create in future in the system and it's no available when user inputs the JsonPath.)

Is that feature available in this library to validate a JsonPath?

**Comment by hf-kklein** [comment]
Did you try

```
JsonPath.compile(“$.your.path”);
```
?
It should throw an InvalidPathException for invalid paths.

**Comment by SaeedZhiany** [comment]
No, I didn't try that and it seems the exact function I need.

I'm closing this issue.

Thanks
