### ISSUE TITLE
When used Gson mapping provider and gson json provider, read operation throws exception of com.google.gson.JsonArray cannot be cast to java.util.list

### ISSUE THREAD

**Issue by vir2610** [json-path/JsonPath#599]
Hi,
I've modified default configuration for reading and mapping json using jsonpath. I am using gson for both providers. I've also added Option.ALWAYS_RETURN_LIST. So now I am expecting every result to be a list, but that is not happening.
Please see below code snippet for my configuration :
`public static final Configuration config = Configuration.builder().options(Option.ALWAYS_RETURN_LIST).jsonProvider(new GsonJsonProvider()).mappingProvider(new GsonMappingProvider()).build();`

Now, I'm using this config while parsing the json string as below :
`DocumentContext ctx = JsonPath.parse(jsonString, config);`

After reading, I am expecting it to be something like this :
`List<String> list = ctx.read("path to read json");`

But I am getting exception as stated in the question : 
`java.lang.ClassCastException : com.google.gson.JsonArray cannot be cast to java.util.List`

Can you please guide me here if I have done configuration right for expecting read values as list ?

**Comment by Alanscut** [comment]
`gson.JsonArray` is not implemented `List`, so it could not be casted to `List`.

I try to fix this issue, but it will introduce some other problem.
hope the following way can solve your problem.
```
JsonArray array = ctx.read("path to read json");
List<String> list = new ArrayList<>();
array.forEach(item -> list.add(item.getAsString()));
```

**Comment by vir2610** [comment]
@Alanscut Got it, thanks for the response. I've also checked the reference you attached in the commit for test class.
