### ISSUE TITLE
Since there no active releases after 2.4.0 our company not recommending this library, can you please let me know if any future releases.

### ISSUE THREAD

**Issue by Muniswamy366** [json-path/JsonPath#616]
Since there no active releases after 2.4.0 our company not recommending this library, can you please let me know if any future releases.

**Comment by harkue** [comment]
A new release is welcomed.

**Comment by jobmission** [comment]
+1

**Comment by valfirst** [comment]
https://github.com/json-path/JsonPath/issues/500
