### ISSUE TITLE
$.concat() function with filters in parameters doesn't work

### ISSUE THREAD

**Issue by KaterynaBoiko** [json-path/JsonPath#620]
Hello!

I want to concatenate several JSON attributes selecting them by filters but face an issue in the library.
When a function's parameter contains parentheses, the path is not compiled.
I tried it several times, but always get the following exception: 
`com.jayway.jsonpath.InvalidPathException: Could not parse token starting at position 26. Expected ?, ', 0-9, * 
`

Sample JSON:

    {
      "complexText": {
        "nestedFields": [
          {
            "index": "0",
            "name": "A"
          },
          {
            "index": "1",
            "name": "B"
          },
          {
            "index": "2",
            "name": "C"
          }
        ]
      }
    }

Sample pathExpr:

    "$.concat($.complexText.nestedFields[?(@.index == '2')].name,$.complexText.nestedFields[?(@.index == '1')].name,$.complexText.nestedFields[?(@.index == '0')].name)"

When I run:
 
    DocumentContext context = ParseContext.using(conf).parse(json)
    context.read(pathExpr);
    
I expected to get the following result:

    "CBA"

However, the actual result is:

    com.jayway.jsonpath.InvalidPathException: Could not parse token starting at position 26. Expected ?, ', 0-9, * 

If I change filters in functions' parameters to explicit indexes, the function works as expected:

    "$.concat($.complexText.nestedFields[2].name,$.complexText.nestedFields[1].name,$.complexText.nestedFields[0].name)"
    
Result:

    "CBA"
    

I debugged json-path library and found an issue in `com.jayway.jsonpath.internal.path.PathCompiler.java`.
When there is a close parenthesis in a function's parameter, it is appended to a parameter twice. 
First in the line [PathCompiler.java:337](https://github.com/json-path/JsonPath/blob/master/json-path/src/main/java/com/jayway/jsonpath/internal/path/PathCompiler.java#L337) and then one more time in the line [PathCompiler.java:370](https://github.com/json-path/JsonPath/blob/master/json-path/src/main/java/com/jayway/jsonpath/internal/path/PathCompiler.java#L370).
Thus, the first parameter of the `$.concat()` function in this path expression 

    "$.concat($.a[?(@.b == 'c')].d, $e)" 
    
is resolved to 
    
    "$.a[?(@.b == 'c'))].d"    // note two close paretheses after 'c'

instead of 
    
    "$.a[?(@.b == 'c')].d"

Could you take a look at this issue, please?

**Comment by CindyChow123** [comment]
Hi @kallestenflo ,I'd like to work on this issue.
