### ISSUE TITLE
How to set array values in jsonPath

### ISSUE THREAD

**Issue by vicya** [json-path/JsonPath#625]
Hello 
My json str `{
    "id":600608970,
    "item":{
        "xxId":"asda",
        "xxitems":[
            {
                "id":10,
                "endDate":"2020-07-20"
            },
            {
                "id":20,
                "endDate":"2020-07-20"
            }]
    }
}`
I want to extract id 10,20 and  change there value to 110,120(add 100）
First , I use `$.item[*].id` to extrat ,  how can I set value in jsonpath ?

**Comment by kallestenflo** [comment]
Please ask questions about usage at [stackoverflow](https://stackoverflow.com/questions/tagged/jsonpath).
