### ISSUE TITLE
Mark json-smart as optional in the manifest file for OSGI

### ISSUE THREAD

**Issue by LaurentT** [json-path/JsonPath#626]
Hello,

Here is my issue:

I explicitly want to exclude json-smart dependency from my project when using json-path since I want to use Jackson (which is still maintained)

However when I deploy my project in an OSGI environment, it complains because it doesn't find the json-smart jar (which is normal because I don't want it)

It happens because of this commit: https://github.com/json-path/JsonPath/commit/aba863021c1ba59234ac0b239e1fce707b3de9a3#diff-97a3df98ab94b662feb8bfb28e05ed3c

I suggest putting this in the build.gradle: 'net.minidev.*;resolution:=optional'
Tested it in my OSGI environment, it works.

I'll create a pull request :)

**Comment by kallestenflo** [comment]
Fixed in 2.6.0
