### ISSUE TITLE
JsonPath.compile("$.A.B.C.D(") returns $['A']['B']['C'].D()

### ISSUE THREAD

**Issue by KumarNavneet** [json-path/JsonPath#629]
Hi,
JsonPath.compile("$.A.B.C.D(") returns $['A']['B']['C'].D() instead of  $['A']['B']['C']['D(']

**Comment by kallestenflo** [comment]
This is an invalid path and should not compile at all.

**Comment by sdmms1** [comment]
Hi, I found the problem is due to the lack of checking the matches of the parenthesises and I would like to contribute to it!
