### ISSUE TITLE
[*] in filter not working 

### ISSUE THREAD

**Issue by umerhamdan10** [json-path/JsonPath#630]
This one working fine 
**$..A[?(@.a.b==  "terz" && @.c.length !=0 && @c.a[0].class== "class2")].x.y.z**

Why this one not working?

**$..A[?(@.a.b==  "terz" && @.c.length !=0 && @c.a[*].class== "class2")].x.y.z**

If this is the not correct way to filter, can you tell me I want apply filter on all object of nested arry not on one. How can I do that?

**Comment by kallestenflo** [comment]
Please provide sample JSON, expected outcome and actual outcome
