### ISSUE TITLE
Is it possible to filter out the specified object from the nested object (map structure)?

### ISSUE THREAD

**Issue by roychen11232357** [json-path/JsonPath#631]
Suppose my input is like this

```
{
    "values": {
        "obj1": {
            "key1": 46,
            "key2": 19
        },
        "obj2": {
            "key1": 10,
            "key2": 20
        }
    },
    "option": "test"
}
```

And I want to filter out the results that meet `values.obj1.key1>20`, the expected output is like this

```
{
    "values": {
        "obj1": {
            "key1": 46
        }
    },
    "option": "test"
}
```

Is it possible to achieve through JsonPath?

**Comment by hf-kklein** [comment]
So the actual filtering is not a problem using the path `$[?(@.values.obj1.key1>=20)]` **but** your expected output is not only a filter but _modifies_ the data because the `obj2` key and `obj1.key2` are removed. Therefore you can use the DocumenteContext `delete` method.
