### ISSUE TITLE
Error java.net.SocketException: getsockname failed: EBADF (Bad file descriptor)

### ISSUE THREAD

**Issue by Dogfree** [json-path/JsonPath#632]
On some devices, throws java.net.SocketException: getsockname failed: EBADF (Bad file descriptor)

It mostly appears on Android 6, but others have encountered it as well.

The exception appears here: 
` UnzipConfig.donate_url = JsonPath.parse(json_url).read("$.donate_url");`

The json_url stores the link

**Comment by kallestenflo** [comment]
Please provide information about version. `JsonPath.parse` no longer accepts `URL`.
