### ISSUE TITLE
Failing regex left match in Jayway engine

### ISSUE THREAD

**Issue by kjozsa** [json-path/JsonPath#640]
Sample input:
```
{
  "image": "a",
  "image2": "b",
  "image3": "c",
  "image4": "d",
  "image5": "e"
}
```
JsonPath expression: `$.[?(@ =~ /image*/)]`
Expected output:
```
[
  "a",
  "b",
  "c",
  "d",
  "e"
]
```
This works with https://jsonpath.com/ 's evaluator but not with Jayway JsonPath :|

**Comment by hf-kklein** [comment]
duplicate of #348

**Comment by kjozsa** [comment]
oops, closing then, sorry. Hope it gets fixed soon!

**Comment by hf-kklein** [comment]
>Hope it gets fixed soon!

don't wanna frustrate you but the original ticket is open since 2017...

**Comment by kjozsa** [comment]
#ohwell 😅 I thought the whole point of applying JsonPath is to write incredibly compact oneliners doing all the heavy lifting..

**Comment by hf-kklein** [comment]
It certainly is but seems like not for all use cases ;)
