### ISSUE TITLE
max() donot work

### ISSUE THREAD

**Issue by apaqi** [json-path/JsonPath#641]
it returns [8.95,12.99, 8.99, 22.99], where I use  $.store.book[?(@.price)].price 
I want to get the max price byusing $.store.book[?(@.price)].price.max() , but it returns nothing.
What is the problem ?

**Comment by kallestenflo** [comment]
This is an old problem with the implementation. You can not apply functions to the "result set" only to arrays in the document. 

```
{
    "array": [8.95,12.99, 8.99, 22.99]
}
```

`$.array.max() `

For now, this is by design.

**Comment by adityapant1286** [comment]
@apaqi 

This maybe late to respond but there is another workaround.

`List<Double> prices = provider.get("$.store.book[:2].price", new TypeRef<>(){});
        final Double sum = JsonPath.parse(prices).read("$.sum()", new TypeRef<>() {});`
