### ISSUE TITLE
when would this software give a new release?

### ISSUE THREAD

**Issue by maxpaynebupt** [json-path/JsonPath#647]
Long time no see, obsoleted?

**Comment by bono007** [comment]
I have a similar question, in that I am trying to understand the current state of this project. Its used in a project I am working on and I am interested in updating the underlying version of asm (used in turn by the json-smart). Which that brings up another question, really what is the state of that project? Is it being driven by Redhat as I see it has activity in the [Redhat repos](https://mvnrepository.com/artifact/net.minidev/json-smart?repo=redhat-ga). 

Any info is greatly appreciated. Thanks in advance.

**Comment by bono007** [comment]
@kallestenflo can you add a comment?

**Comment by kallestenflo** [comment]
Sorry! It has been released.

**Comment by maxpaynebupt** [comment]
> Sorry! It has been released.
> […](#)
> Sent from my iPhone
> On 10 Dec 2020, at 15:53, bono007 ***@***.***> wrote: ﻿ @kallestenflo can you add a comment? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

love you sososososo much.
