### ISSUE TITLE
a bug about regular expression 

### ISSUE THREAD

**Issue by hakusa** [json-path/JsonPath#658]
when  execute `read("$.store.book[?(@.display-price>=8 &&  @.category=~ /.*reference.*/)]") ` can get right result,
but  execute `read("$.store.book[?( @.category=~ /.*reference.*/&& @.display-price>=8 )]")  `  get wrong result.
I guess there's a bug in the function `com.jayway.jsonpath.internal.filter.FilterCompiler.readPattern()`

**Comment by FSchumacher** [comment]
The same bug seems to have been reported in JMeter [Bug 65053](https://bz.apache.org/bugzilla/show_bug.cgi?id=65053). A git bisect on JsonPath repo points to the addition of support for pattern flags with cbdc9c82e00edb9496f41a4aca3d12ef7ee8321b.

**Comment by npoirey** [comment]
Hi,

Can we have an ETA on a probable merge/release including the fix ? (I'm not complaining, just asking to get an idea if it's pertinent for me to temporarily copy FSchumacher fork and use it in the meantime :) )

Thanks

**Comment by kallestenflo** [comment]
Fixed in version 2.6.0
