### ISSUE TITLE
Possible NoClassDefFoundError Bug

### ISSUE THREAD

**Issue by kayak503** [json-path/JsonPath#666]
When working with JsonPath every now and again Java will through a `NoClassDefFoundError:` pointing to `com/jayway/jsonpath/Predicate`. 
The error will pop up after compiling and appear on every instance of that java file, only disappearing after a recompile. when I recompile none of the code changes yet the error will disappear. Since no code changes I assume the error has something to do with my compiler/IDE rather then a bug with JsonPath. If anyone else has this issue feel free to comment I will continue exploring this phenomenon and will update the post if anything changes  

```
Caused by: java.lang.ClassNotFoundException: com.jayway.jsonpath.Predicate
NoClassDefFoundError: com/jayway/jsonpath/Predicate
```

**Comment by kallestenflo** [comment]
Don't see this as a JsonPath issue. Probably IDE related.
