### ISSUE TITLE
using .set to add JSONArray will result in empty array in output of jsonString method

### ISSUE THREAD

**Issue by dbelyaev** [json-path/JsonPath#669]
Hello, 

I am trying to replace values in field which is `JSONArray` using `set` method from `DocumentContext` object.
This gives me then an empty array when I try to get json as string via `jsonString()` method available  from `DocumentContext`.

Here is an example code:

```
// init json array
JSONArray emails = new JSONArray();
emails.put("user1@email.org");
emails.put("user2@email.org");

// init DocumentContext and set array to the specic field
DocumentContext context =  JsonPath.parse("{ \"emails\": [\"test@email.org\"] }");
context.set("emails", emails);
String jsonString = context.jsonString();
```
As a result I expect `jsonString` variable to have a value:
```
{
	"emails": [
		"user1@email.org",
		"user2@email.org"
	]
}
```
but it gives me:
```
{
	"emails": {}
}
```

Am I using this set functionality wrongly or is it a bug?

**Comment by CoddingApe** [comment]
try .add :)

**Comment by dbelyaev** [comment]
@CoddingApe no, does not work. When using `.add` it returns:

```
"emailRecipients": [
    "test-user1@equinor.com",
    "test-user2@equinor.com",
    {}
]
```

**Comment by dbelyaev** [comment]
@CoddingApe no, it does not work neither.

This part of code:
```
// init json array
JSONArray emails = new JSONArray();
emails.put("user1@email.org");
emails.put("user2@email.org");

// init DocumentContext and set array to the specific field
DocumentContext context =  JsonPath.parse("{ \"emails\": [\"test1@email.org\", \"test2@email.org\"] }");
context.add("emails", emails);
String jsonString = context.jsonString();
```
Will return:
```
{
    "emails": [
        "test1@email.org",
        "test2@email.org",
        {}
    ]
}
```
Looks like `.add` method is trying to add JSONArray instance as an extra array-element in existing array.

Same goes from debug output:
![image](https://user-images.githubusercontent.com/6915328/107015510-197bc400-679d-11eb-9b6e-a25f7d6b3429.png)

**Comment by CoddingApe** [comment]
> @CoddingApe no, it does not work neither.
> 
> This part of code:
> 
> ```
> // init json array
> JSONArray emails = new JSONArray();
> emails.put("user1@email.org");
> emails.put("user2@email.org");
> 
> // init DocumentContext and set array to the specific field
> DocumentContext context =  JsonPath.parse("{ \"emails\": [\"test1@email.org\", \"test2@email.org\"] }");
> context.add("emails", emails);
> String jsonString = context.jsonString();
> ```
> 
> Will return:
> 
> ```
> {
>     "emails": [
>         "test1@email.org",
>         "test2@email.org",
>         {}
>     ]
> }
> ```
> 
> Looks like `.add` method is trying to add JSONArray instance as an extra array-element in existing array.
> 
> Same goes from debug output:
> ![image](https://user-images.githubusercontent.com/6915328/107015510-197bc400-679d-11eb-9b6e-a25f7d6b3429.png)

well, I tested your code and change JSONArray into List<String>, it works.

// init json array
    List<String> emails = new ArrayList<>();
    emails.add("user1@email.org");
    emails.add("user2@email.org");

// init DocumentContext and set array to the specic field
    DocumentContext context = JsonPath.parse("{ \"emails\": [\"test@email.org\"] }");
    context.set("emails", emails);
    String jsonString = context.jsonString();
    System.out.println(jsonString);

output : {"emails":["user1@email.org","user2@email.org"]}

**Comment by CoddingApe** [comment]
@dbelyaev I test your code, and change JSONArray into List<String>, the problem fixed.
    // init json array
    List<String> emails = new ArrayList<>();
    emails.add("user1@email.org");
    emails.add("user2@email.org");

// init DocumentContext and set array to the specic field
    DocumentContext context = JsonPath.parse("{ \"emails\": [\"test@email.org\"] }");
    context.set("emails", emails);
    String jsonString = context.jsonString();
    System.out.println(jsonString);

here's the output : {"emails":["user1@email.org","user2@email.org"]}

**Comment by CoddingApe** [comment]
@dbelyaev I test your code and change JSONArray into List<String> and solved the problem.
`    // init json array
    List<String> emails = new ArrayList<>();
    emails.add("user1@email.org");
    emails.add("user2@email.org");

// init DocumentContext and set array to the specic field
    DocumentContext context = JsonPath.parse("{ \"emails\": [\"test@email.org\"] }");
    context.set("emails", emails);
    String jsonString = context.jsonString();
    System.out.println(jsonString);`

output is : `{"emails":["user1@email.org","user2@email.org"]}`

**Comment by CoddingApe** [comment]
@dbelyaev I tested your code, and change JSONArray into List<String> and solved the problem.

```
// init json array
    List<String> emails = new ArrayList<>();
    emails.add("user1@email.org");
    emails.add("user2@email.org");

// init DocumentContext and set array to the specic field
    DocumentContext context = JsonPath.parse("{ \"emails\": [\"test@email.org\"] }");
    context.set("emails", emails);
    String jsonString = context.jsonString();
    System.out.println(jsonString);
```
output :
`{"emails":["user1@email.org","user2@email.org"]}`

**Comment by dbelyaev** [comment]
@CoddingApe thanks a lot now it is working, closing this issue!

**Comment by krakzk** [comment]
@CoddingApe  If i have an array of Object, this is still not working
Tried both as JSONArray and a List<Object>
Didnt work
