### ISSUE TITLE
Is the a way to Save back the JSON file?

### ISSUE THREAD

**Issue by Ebest01** [json-path/JsonPath#686]
Am loading JSON from a FILE, I'd like a way to set NEW Value and SAVE back the file.

Any Help will be highly appreciated

```
$json_file = file_get_contents('myJSON.json');
 
 $json_Obj = new JsonObject($json_file);
 
$json_Obj ->set("$.user.name",'User New Name is Peter');
```
//This is where am lost .>> `file_put_contents('myJSON.json',"?????????"); // What to put here?`

`//Any idea how do you Save the File after editing the JSON contents in the myJSON.json file?`

Thank you very much

**Comment by kallestenflo** [comment]
Not related to this project
