### ISSUE TITLE
JsonPath.parse does not throw `InvalidJsonException` when malformed extra symbols are after a valid serialized json string

### ISSUE THREAD

**Issue by andrii-kovalenko-celonis** [json-path/JsonPath#689]
**When**:
```java
final DocumentContext parsed = JsonPath.parse("\"components\"OOPS?");
```

**Expected**:
`InvalidJsonException` is thrown

**Actual**:
`parsed` assigned a _valid_ `DocumentContext` with a single string `"components"`

Seems like a bug, as neither the [Standard](https://www.json.org/json-en.html) nor other parser realize it as a valid serialized JSON.

**Having**:
`com.jayway.jsonpath:json-path:2.5.0`
`openjdk version "11.0.10" 2021-01-19  (build 11.0.10+9-Ubuntu-0ubuntu1.18.04)`
`OS: Ubuntu 18.04.5 LTS`

**Comment by Youngea** [comment]
It seems that it is the mode of the provider you choose. If you choose a `strict_mode`, the InvalidJsonException throws. And it can be generated like:
```
        String invalid = "\"components\"OOPS?";
        Configuration conf = Configuration.defaultConfiguration();
        conf = conf.jsonProvider( new JsonSmartJsonProvider(JSONParser.MODE_STRICTEST));
        Object res = JsonPath.using(conf).parse(invalid);
```

**Comment by andrii-kovalenko-celonis** [comment]
true.
Also works with either `USE_INTEGER_STORAGE`  or `USE_HI_PRECISION_FLOAT`.
Just realized by default it is `MODE_PERMISSIVE`:
> smart mode, fastest parsing mode. accept lots of non standard json syntax

This could be configured by system property `JSON_SMART_SIMPLE`:
https://github.com/netplex/json-smart-v1/blob/master/json-smart/src/main/java/net/minidev/json/parser/JSONParser.java#L111-L112
