### ISSUE TITLE
`Expected character: )` in Regex + Boolean operator expression (Invalid filter)

### ISSUE THREAD

**Issue by moshevi** [json-path/JsonPath#692]
This is my JSON
`
{
  "a": {
    "b": "cdefg"
  }
}
`

This is my JayWay JsonPath expression
`[?((($.a.b =~ /cd.*/) && ($.a.b == 'cdefg')))]`

I'm getting an error `Expected character: )` when running [here](https://jsonpath.herokuapp.com/) 
Any reason why ?

BTW, if i'm changing sides of operands, like so `[?((($.a.b == 'cdefg') && ($.a.b =~ /cd.*/)))]` it matches OK

**Comment by Chaoyi-1230** [comment]
Hii, I am curious on your issue but I think I did not get it right.

I tested the project according to your issue as below:

`@Test
    // https://github.com/jayway/JsonPath/issues/692
    public void issue692() {
        final String jsonDemo = "{ \"a\": { \"b\": \"cdefg\" } }";
        final ReadContext context = JsonPath.parse(jsonDemo);
        final Filter validFilter = Filter.parse("[?((($.a.b == 'cdefg') && ($.a.b =~ /cd.*/)))]");
        final Filter invalidFilter = Filter.parse("[?((($.a.b =~ /cd.*/) && ($.a.b == 'cdefg')))]");
        assertThat(validFilter.apply(createPredicateContext(context))).isEqualTo(invalidFilter.apply(createPredicateContext(context)));
    }`

And the outcome seems alright. Would you kindly let me know if I did not get your problem?

**Comment by moshevi** [comment]
I've tested that on the evaluator at https://jsonpath.herokuapp.com/
`[?((($.a.b == 'cdefg') && ($.a.b =~ /cd.*/)))]` is a valid filter and return filter results
`[?((($.a.b =~ /cd.*/) && ($.a.b == 'cdefg')))]` isn't a valid filter and return with error `Expected character: )`

**Comment by moshevi** [comment]
@Chaoyi-1230 Any updates on my last comments?

**Comment by Chaoyi-1230** [comment]
Hii moshevi, sorry for the delay.

I have verified the problem you pointed out, and I am trying to fix it now.

Anyone else is interested in this issue is welcome to take part in :)

**Comment by moshevi** [comment]
@Chaoyi-1230 Any progress on fixing this?

**Comment by moshevi** [comment]
I see there's a fix for that on [(https://github.com/json-path/JsonPath/pull/661/commits/e68e9f2f9b04d741b85797335ac78f1a8c7317c2)]
Any idea when that will be released?

**Comment by kallestenflo** [comment]
Fixed in release 2.6.0
