### ISSUE TITLE
Issue in parsing the following filters  $.rootElement[*].[paramater1,parameter2]

### ISSUE THREAD

**Issue by Saurav4827** [json-path/JsonPath#705]
{
root:
[
{"parameter1":"a",
"parameter2": "b"
},
{
"parameter1":"a",
"parameter2": "b"
}
]
}

App is showing the output in editor , for e.g ["a","b","a",b"]

but while using the filter in JSONPath .....showing error in parsing the above filter

and second thing .. Is there any way to get more than one parameter/attribute in result for an object in single instance

**Comment by hezonghan** [comment]
Hello! Try to add quotes on `root` in the Json string, and on `parameter1`, `parameter2` in the filter?
By the way, there seems to be spelling mistake with `paramater2` (as shown in the issue title)?

**Comment by kallestenflo** [comment]
`$.rootElement[*].[paramater1,parameter2]` is not a valid path.

Questions about usage  are redirected to [Stackoverflow](https://stackoverflow.com/questions/tagged/jsonpath)
