### ISSUE TITLE
jsonpath result introduce escape char by mistake.

### ISSUE THREAD

**Issue by vertigo17** [json-path/JsonPath#707]
Hello,

I am using JsonPath library into my java project called [Cerberus](https://github.com/cerberustesting/cerberus-source).

I found an [issue](https://github.com/cerberustesting/cerberus-source/issues/2240) that could be linked on the way I use your library.

Basicly, If I try to parse that JSON string :

```
{
  "phoneNumbers": [
    {
      "type"  : "iPhone / test",
      "number": "0123-4567-8888"
    },
    {
      "type"  : "home",
      "number": "0123-4567-8910"
    }
  ]
}
```

with JSONPath:

`$.phoneNumbers[*].type`

I get that result:

`["iPhone \/ test","home"]`

When I expected:

`["iPhone / test","home"]`

An escape char is introduced before the /

I use the following code with version 2.5.0:

```
Object obj = JsonPath.read(json, jsonPath);
return String.valueOf(obj);
```

How can I remove that extra escape char ? Am I doing something wrong ?

Thanks.

**Comment by CindyChow123** [comment]
You can use `JSONValue.COMPRESSION = JSONStyle.LT_COMPRESS;` to fix this problem.

**Comment by vertigo17** [comment]
Thanks. It solved the issue.
