### ISSUE TITLE
Using DocumentContext if an intermediate path is read more than once then it returns nothing

### ISSUE THREAD

**Issue by debdayal** [json-path/JsonPath#717]
I am using DocumentCotext to parse the file once. And then trying to extract List<Map> using JsonPath. First time i am getting proper result but subsequent call on the same DocumentCotext read() returns blank[] array.

`Configuration conf = Configuration.builder().options(
			Option.ALWAYS_RETURN_LIST, Option.DEFAULT_PATH_LEAF_TO_NULL, Option.SUPPRESS_EXCEPTIONS).build();
DocumentContext document = JsonPath.using(conf).parse(json);
//call 1: Good => returns value
List<Map<String, Object>> list = document.read("$.consents[?('abc' in @.products)]");

//call 2: Good => returns blank
List<Map<String, Object>> list1 = document.read("$.consents[?('abc' in @.products)]");

//call 3: Good => returns blank
List<Map<String, Object>> list2 = document.read("$.consents[?('cde' in @.products)]");
`
JsonPath Version in use:
<dependency>
    	<groupId>com.jayway.jsonpath</groupId>
    	<artifactId>json-path</artifactId>
    	<version>2.5.0</version>
</dependency>

**Comment by hezonghan** [comment]
Hello! I tested your issue with the following code:
```
        Configuration conf = Configuration.builder().options(
                Option.ALWAYS_RETURN_LIST, Option.DEFAULT_PATH_LEAF_TO_NULL, Option.SUPPRESS_EXCEPTIONS).build();
        DocumentContext document = JsonPath.using(conf).parse(
                "{consents:[" +
                        "{\"id\":1 , \"products\": [\"abcde\" , \"abc\"] }," +
                        "{\"id\":2 , \"products\": [\"deabc\"] }" +
                        "{\"id\":3 , \"products\": [\"de\"] }" +
                        "]}");

        String path = "$.consents[?('abc' in @.products)]";
        List<Map<String,Object>> list0 = document.read(path);
        List<Map<String,Object>> list1 = document.read(path);
        List<Map<String,Object>> list2 = document.read(path);

        System.out.println(list0);
        System.out.println(list1);
        System.out.println(list2);
```
using the newest forked code.
The output is:
```
[{"id":1,"products":["abcde","abc"]}]
[{"id":1,"products":["abcde","abc"]}]
[{"id":1,"products":["abcde","abc"]}]
```
It seems that the results for the second and third reading are not blank.

**Comment by debdayal** [comment]
@hezonghan I think i got the issue. My situation was after receiving the List<Map> i was removing the products from the output but that was impacting the DocumentContext itself. So the output of document.read() is not a deep copy of the json. Run the below code snippet then you will see the same. Not sure if this a defect here. 

Configuration conf = Configuration.builder().options(
                Option.ALWAYS_RETURN_LIST, Option.DEFAULT_PATH_LEAF_TO_NULL, Option.SUPPRESS_EXCEPTIONS).build();
        DocumentContext document = JsonPath.using(conf).parse(
                "{consents:[" +
                        "{\"id\":1 , \"products\": [\"abcde\" , \"abc\"] }," +
                        "{\"id\":2 , \"products\": [\"deabc\"] }" +
                        "{\"id\":3 , \"products\": [\"de\"] }" +
                        "]}");

        String path = "$.consents[?('abc' in @.products)]";
        List<Map<String,Object>> list0 = document.read(path);
        
        //do something with list0
        list0.stream().forEach(item -> {
        	System.out.println(item);
        	item.remove("products");
        });
        
        List<Map<String,Object>> list1 = document.read(path);
        List<Map<String,Object>> list2 = document.read(path);

        System.out.println(list0);
        System.out.println(list1);
        System.out.println(list2);
