### ISSUE TITLE
How do i filter the resultset json using JsonPath lib? 

### ISSUE THREAD

**Issue by Sriram1404** [json-path/JsonPath#725]
"resultset": [
        {
            "a": {
                "b": {
                    "c": [
                        {
                            "d": "Agricultural Business and Management.",
                            "e": {
                                "f": "Bachelors Degree"
                            }
                        },
                        {
                            "d": "Agricultural Business and Management.",
                            "e": {
                                "f": "Master's Degree"
                            }
                        }
					]
				}
			}
		}
	]

Above is my result set json i want to do filter based on d and f json nodes. I want to check whether there exist [Master degree] in [Agricultural and Business and Management] exist in  result set json. Please provide the sample example for better understanding.

**Comment by kallestenflo** [comment]
Try `$[*].a.b.c[?(@.d == "Agricultural Business and Management." && @.e.f == "Master's Degree")]`

Please ask question about usage at [Stackoverflow](https://stackoverflow.com/questions/tagged/jsonpath)
