### ISSUE TITLE
OSGi build plugin is deprecated since Gradle 5.0

### ISSUE THREAD

**Issue by greek1979** [json-path/JsonPath#727]
The OSGi plugin for Gradle has been officially deprecated since Gradle 5.0 is out, and will be probably removed in the coming year or so. Gradle site says:

> New builds should not use this plugin. A separate plugin implementation is maintained by the BND authors that has more advanced features.

Source: https://docs.gradle.org/5.0/userguide/osgi_plugin.html

However, the JsonPath parent build.gradle script uses the OSGi plugin; can it be replaced with the BND tool as described here: 
https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/README.md#replacing-use-of-gradles-deprecated-osgi-plugin ?

**Comment by kallestenflo** [comment]
Fixed by #730
