### ISSUE TITLE
The jcenter() Gradle method is deprecated

### ISSUE THREAD

**Issue by greek1979** [json-path/JsonPath#728]
From https://docs.gradle.org/7.0.1/userguide/upgrading_version_6.html#jcenter_deprecation :

> The jcenter() convenience method is now deprecated. JFrog announced the decommission of JCenter. This has the potential to impact many Gradle builds. Gradle emits a deprecation warning when jcenter() is used in the repository configuration. Consider using mavenCentral(), google() or a private maven repository instead.

Original news: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter

**Comment by kallestenflo** [comment]
Fixed by #730
