### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by richardstartin** [json-path/JsonPath#754]
This library is widely used but PRs do not seem to be responded to. 

If the library is no longer maintained, it would be best if maintainership could be handed over to someone willing to review, merge, and release changes. This is better than forking, which would require new maven coordinates.

Is anyone using the library willing to do maintenance, and are the current maintainers interested in handing over the organisation to a potential maintainer?

**Comment by greek1979** [comment]
I had the same question around half a year ago (before submitting a number of PR myself, to fill in the gaps in the missing functionality of JsonPath). Things haven't been progressing - until late October '21, then something changed and PR's started being reviewed and approved, and code being updated. I guess it will take some time for maintainers to review and approve (or correct / discard) all accumulated PR's ... :-)

**Comment by richardstartin** [comment]
This library is very widely used (I don't think it's an exaggeration to call it a bedrock library - [here](https://mvnrepository.com/artifact/com.jayway.jsonpath/json-path/2.6.0/usages) are the users of the latest release) and as far as I can tell, its maintenance depends on a single maintainer, @kallestenflo, so it's completely understandable that things take time. On the other hand, it is incomplete, has performance problems and bugs, and because it's so widely used these things do need fixing in a timely manner. Of course, the source code is available so anybody can fork and release changes, but I don't think that's a good outcome, especially if the fork ends up with a single maintainer who doesn't have the time to be responsive. 

So my question is does anybody want to help and can @kallestenflo delegate some of the maintenance burden so things can move faster?

**Comment by valfirst** [comment]
have anyone stepped in and forked the project?
