### ISSUE TITLE
Release 2.7.0 ETA

### ISSUE THREAD

**Issue by richardstartin** [json-path/JsonPath#768]
There are several fixes for performance bottlenecks on master now. Is there any chance these could be released soon? What is the ETA?

**Comment by r0goyal** [comment]
@kallestenflo Please help with the ETA for next release

**Comment by r0goyal** [comment]
@kallestenflo Any update on this ?

**Comment by r0goyal** [comment]
@kallestenflo Any update on this ?

**Comment by kallestenflo** [comment]
json-path-2.7.0 is released. May take a couple of hours before it's available in Maven Central.

**Comment by r0goyal** [comment]
Thanks @kallestenflo
