### ISSUE TITLE
search elements in non-array failed.

### ISSUE THREAD

**Issue by CNEric1949** [json-path/JsonPath#847]
json like:
```
{
    "store": {
          "a": {
               "desc": "A"
          },
          "b": {
              "desc": "B"
          }
     }
}
```

path like:
`$.store[?(@.desc=='A')]`

expect:
`[
   {
      "desc" : "A"
   }
]`

in fact:
`[
]`

gatling with old version or goessner works fine.

it can be found on the following online evaluator.

http://jsonpath.herokuapp.com/

**Comment by goelsourabh** [comment]
Path should be $.store..[?(@.desc=='A')].

**Comment by CNEric1949** [comment]
> Path should be $.store..[?(@.desc=='A')].

jsonpath should be this one.
