### ISSUE TITLE
Extract specific word from value using regular expression 

### ISSUE THREAD

**Issue by goelsourabh** [json-path/JsonPath#848]
Hi,

I have a requirement where I can extract specific word from json value. A value is actually a sentence having many words. e.g.
 
**Json message:**

{
    "code": "xfhff32239jg5",
    "otherField": "This is a test data, trying to find only this number 23423543435, other words should not be extracted"
}

**Json path**: 

$.[?(@.otherField =~ /.*23423543435.*/)].otherField

Using above data and json path expression, I am getting below extract:
[
   "This is a test data, trying to find only this number 23423543435, other words should not be extracted"
]

But, my requirement is to extract only "23423543435" based json path expression. It means that we need a json path expression having regular expression which extract the specific word from the given sentence. So, below is my expectation:
[
   "23423543435"
]
See example in https://regex101.com/r/mV0iS3/1, where we can see the match and group(s). So, I require to fetch specific group only and not the complete value of json field. I tried to build a json path expression along with regular expression to extract specific "group" but I couldn't make such expression. Is it currently supported/implemented?

Any input will be a great help.

Best Regards
Sourabh Goel

**Comment by Ahona1186** [comment]
You can extract the JSON value from the required path anyway and then extract the only numeric characters off that value. You will temporarily store the value in a string, read only the numeric part of use a regex on it to extract and then move to the next array element

**Comment by MeeKapil** [comment]
Below code will extract only numbers and will remove remaining characters with space:

ReadContext ctx = JsonPath.parse(json);
String numericOnly = ctx.read("$.otherField").toString().replaceAll("[^0-9]", ""));

**Comment by goelsourabh** [comment]
Hello Ahona1186 and MeeKapil , thank you both for your valuable time to look into this issue and provide solution. **But, this is not the requirement.** Above solutions will require to enhance in the application code. I was looking for **Json-path expression** which actually extract part of required text. In other words, json-path library should have been a capability to provide these kind of extractions **out-of-the-box**, but finally I found that its not available.

Best Regards
Sourabh Goel
