### ISSUE TITLE
json-path 2.7.0 vulnerabilities should be fixed

### ISSUE THREAD

**Issue by alainlompo** [json-path/JsonPath#889]
# What?
Json-path 2.7.0 seems to have a number of vulnerabilities that should be fixed

## To reproduce

Simply browse to: https://mvnrepository.com/artifact/com.jayway.jsonpath/json-path/2.7.0

**Comment by UcanInfosec** [comment]
@alainlompo please see the following as they are being addressed. https://github.com/json-path/JsonPath/pull/869
https://github.com/json-path/JsonPath/pull/866

**Comment by UcanInfosec** [comment]
Would argue this should be closed

**Comment by alainlompo** [comment]
@UcanInfosec thank you. Allright, then I close this issue.

**Comment by alainlompo** [comment]
Being addressed in #869 and #866
