### ISSUE TITLE
Heroku environment down

### ISSUE THREAD

**Issue by RomainTHD** [json-path/JsonPath#901]
The deployment <a href="https://jsonpath.herokuapp.com/">https://jsonpath.herokuapp.com/</a> is down.

Related to #886

**Comment by danielaparker** [comment]
Down forever, heroku has shut down their free services from November 28, 2022. @psumiya has kindly provided an alternative, https://sumiya.page/jpath.html

**Comment by tresni** [comment]
I stood up an instance of the webapp on Fly.io - https://jsonpath.fly.dev/
