### ISSUE TITLE
Github release notes for 2.8.0 are missing

### ISSUE THREAD

**Issue by Ernir** [json-path/JsonPath#912]
This makes 2.7.0 show up as the latest release on the main Github project page, see:

![image](https://user-images.githubusercontent.com/3148055/228771106-1eda28df-6f64-4ccc-80da-de1cb1fcb0a1.png)

I noticed this because we use a bot to create links to releases of dependency upgrade PRs, and the bot couldn't find a link to 2.8.0. :)

Thanks!

**Comment by kallestenflo** [comment]
Fixed

**Comment by Ernir** [comment]
Thank you!
